// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// import 'dotenv/config';
import { defineConfig } from 'prisma/config';
import { env } from './src/config/env';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: `mysql://${env.db.user}:${env.db.password}@${env.db.host}:${env.db.port}/${env.db.name}`,
    shadowDatabaseUrl: `mysql://${env.db.user}:${env.db.password}@${env.db.host}:${env.db.port}/${env.db.shadowName}`,
  },
});
